# Generated by Django 5.0.2 on 2024-02-15 13:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_like_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.user_directory_path),
        ),
    ]
